name: CompSciPy
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_0
  - autograd=1.2=py36_0
  - backcall=0.1.0=py_0
  - blas=1.1=openblas
  - bleach=2.1.3=py_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - cycler=0.10.0=py36_0
  - cython=0.28.2=py36_0
  - dask-core=0.17.4=py_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1
  - fastcache=1.0.2=py36_0
  - freetype=2.8.1=0
  - future=0.16.0=py36_0
  - gmp=6.1.2=0
  - gmpy2=2.0.8=py36_1
  - h5py=2.7.1=py36_2
  - hdf5=1.10.1=2
  - html5lib=1.0.1=py_0
  - imageio=2.3.0=py36_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_1
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - joblib=0.11=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py_0
  - keras=2.1.5=py36_0
  - kiwisolver=1.0.1=py36_1
  - libgfortran=3.0.0=0
  - libgpuarray=0.7.5=0
  - libpng=1.6.34=0
  - libprotobuf=3.5.2=0
  - libsodium=1.0.16=0
  - libtiff=4.0.9=0
  - llvmlite=0.23.0=py36_1
  - mako=1.0.7=py36_0
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.3=py36_1
  - mock=2.0.0=py36_0
  - mpc=1.1.0=4
  - mpfr=3.1.5=0
  - mpmath=1.0.0=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - networkx=2.1=py36_0
  - notebook=5.4.1=py36_0
  - numba=0.38.0=py36_0
  - numexpr=2.6.5=py36_0
  - numpy=1.14.3=py36_blas_openblas_200
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=7
  - openssl=1.0.2o=0
  - pandas=0.22.0=py36_1
  - pandoc=2.2=hde52d81_0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.0=py_0
  - patsy=0.5.0=py36_0
  - pbr=4.0.2=py_0
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.1.0=py36_0
  - pip=9.0.3=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - protobuf=3.5.2=py36_0
  - ptyprocess=0.5.2=py36_0
  - pygments=2.2.0=py36_0
  - pygpu=0.7.5=py36_0
  - pymc3=3.4.1=py36_0
  - pyparsing=2.2.0=py36_0
  - python=3.6.5=1
  - python-dateutil=2.7.2=py_0
  - pytz=2018.4=py_0
  - pywavelets=0.5.2=py36_1
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_4
  - readline=7.0=0
  - scikit-image=0.13.1=py36_0
  - scikit-learn=0.19.1=py36_blas_openblas_201
  - scipy=1.1.0=py36_blas_openblas_200
  - seaborn=0.8.1=py36_0
  - send2trash=1.5.0=py_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.20.1=2
  - statsmodels=0.8.0=py36_0
  - sympy=1.1.1=py36_0
  - tensorflow=1.0.0=py36_0
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - theano=1.0.1=py36_1
  - tk=8.6.7=0
  - toolz=0.9.0=py_0
  - tornado=5.0.2=py36_0
  - tqdm=4.23.3=py_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_0
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=1
  - zlib=1.2.11=0
  - pip:
    - dask==0.17.4
prefix: /Users/yoavram/miniconda3/envs/CompSciPy

